#!/bin/sh
# Put per-device state on /data, so the rootfs never has to be written.
#
# Four things wrote to the rootfs before this existed (measured 2026-09-19 by
# diffing a booted board against the built image):
#
#   /etc/ssh/ssh_host_*                  absent from the image, made at 1st boot
#   /etc/machine-id                      0 bytes in the image, filled by systemd
#   /var/lib/systemd/timesync/clock      rewritten PERIODICALLY -- the risky one
#   /etc/resolv.conf                     symlink into /etc, written on lease
#
# This handles the two that must persist AND can be handled from userspace.
# machine-id cannot: systemd reads it as PID 1, long before any unit could bind
# a file over it, so on a read-only root it becomes transient and is regenerated
# every boot. Do not key fleet identity to it -- use the SoC serial from
# /proc/device-tree/serial-number, which survives a reflash and needs no
# writable storage at all. resolv.conf is left to systemd-resolved, which keeps
# the real file under /run.
#
# Bind mounts rather than symlinks: a symlink out of /etc would be followed
# before /data is mounted during early boot, and would resolve to nothing.
set -eu

STATE=/data/state

# BusyBox has no install(1) and this image ships no coreutils.
mkdir -p "$STATE/ssh" "$STATE/timesync"
chmod 0755 "$STATE/ssh"
chown systemd-timesync:systemd-timesync "$STATE/timesync" 2>/dev/null || true

# --- ssh host keys --------------------------------------------------------
# Without this the keys live on the rootfs and are regenerated by every
# reflash, so every operator gets a MITM warning and learns to ignore it.
mount --bind "$STATE/ssh" /etc/ssh 2>/dev/null || true
if [ -z "$(ls -A /etc/ssh 2>/dev/null | grep '^ssh_host_' || true)" ]; then
    # First boot on this device: generate into what is now /data.
    ssh-keygen -A >/dev/null 2>&1 || true
fi

# sshd needs its config, which lives in the image, not in the state dir.
for f in /usr/share/schultz-state/ssh/*; do
    [ -e "$f" ] || continue
    b=$(basename "$f")
    [ -e "/etc/ssh/$b" ] || cp "$f" "/etc/ssh/$b"
done

# --- timesyncd's clock file -----------------------------------------------
# Touched on a schedule, so it is the one most likely to be mid-write when a
# battery machine loses power. Persisting it also means the clock does not
# start at the image epoch on a board with no RTC.
mkdir -p /var/lib/systemd/timesync 2>/dev/null || true
mount --bind "$STATE/timesync" /var/lib/systemd/timesync 2>/dev/null || true

echo "persistent state bound from $STATE"
