# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "schultz"
BBFILE_PATTERN_schultz = "^${LAYERDIR}/"
BBFILE_PRIORITY_schultz = "10"

# Release codenames this layer has been developed/tested against.
LAYERSERIES_COMPAT_schultz = "scarthgap wrynose"
