# Extends meta-rauc's generic rauc-conf.bb (see
# meta-rauc/recipes-core/rauc/rauc-conf.bb) with theSchultzYocto's actual
# system.conf and keyring cert, per meta-rauc's own documented extension
# mechanism (its example system.conf literally says to do this via a
# bbappend).

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

# development-1.cert.pem is the PUBLIC cert generated by
# scripts/generate-signing-keys.sh -- safe to commit (unlike
# development-1.key.pem, the private key, which stays outside the repo in
# ../keys/ and is gitignored). This gets embedded on-target as the trusted
# keyring for verifying future RAUC bundles.
#
# Tried referencing ../keys/development-1.cert.pem directly via an absolute
# file:// URI first (matching how RAUC_KEY_FILE/RAUC_CERT_FILE work in
# schultz-bundle.bb) -- that does NOT work here. do_fetch's debug log showed
# it took a different code path for the absolute path than for the
# FILESEXTRAPATHS-resolved system.conf, and never actually staged the file
# into WORKDIR, so do_install failed with "No such file or directory".
# Copying the cert into files/ (as meta-rauc's own docs literally show,
# expecting you to "overwrite example ca.cert.pem") avoids the whole issue.
RAUC_KEYRING_FILE = "development-1.cert.pem"

# system.conf ships a literal `compatible=` so the file stays readable and
# greppable, but the bundle derives its own from ${MACHINE} -- a mismatch means
# the target refuses every update. Rewrite it here from the same variable so
# one source of truth survives a change of board.
do_install:append() {
    f="${D}${sysconfdir}/rauc/system.conf"
    [ -f "$f" ] || bbfatal "expected rauc system.conf at $f -- update rauc-conf.bbappend"
    sed -i -e 's/^compatible=.*/compatible=theSchultzYocto-${MACHINE}/' "$f"
    grep -q '^compatible=theSchultzYocto-${MACHINE}$' "$f" || \
        bbfatal "failed to set compatible= in $f"
}

