# Extends meta-rauc's generic rauc-conf.bb (see
# meta-rauc/recipes-core/rauc/rauc-conf.bb) with theSchultzYocto's actual
# system.conf and keyring cert, per meta-rauc's own documented extension
# mechanism (its example system.conf literally says to do this via a
# bbappend). Wildcard PV match since the upstream recipe doesn't pin one.

FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

# The dev cert generated by scripts/generate-signing-keys.sh -- lives
# outside the repo (../keys/, gitignored), same as RAUC_KEY_FILE/
# RAUC_CERT_FILE in schultz-bundle.bb. RAUC_KEYRING_FILE must stay just the
# basename (do_install reads ${WORKDIR}/${RAUC_KEYRING_FILE} after fetch);
# the actual source location is RAUC_KEYRING_URI.
RAUC_KEYRING_FILE = "development-1.cert.pem"
RAUC_KEYRING_URI = "file://${TOPDIR}/../keys/development-1.cert.pem"
